services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: megabot
    restart: unless-stopped
    network_mode: bridge
    dns:
      - 8.8.8.8
      - 1.1.1.1
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8080
      - DOWNLOAD_DIR=/app/downloads
      - SESSION_DIR=/app/sessions
    ports:
      - "8000:8000"
    volumes:
      - ./downloads:/app/downloads
      - ./sessions:/app/sessions
